targets:
  $default:
    builders:
      json_serializable|json_serializable:
        enabled: true
        generate_for:
          - lib/src/models/*.dart
        options:
          explicit_to_json: true
          include_if_null: false
          field_rename: snake

      freezed|freezed:
        enabled: true
        generate_for:
          - lib/src/models/*.dart